---
- hosts: target01
  tasks:
    - name: install packages
      yum: name={{item}} state=installed
      with_items:
        - httpd
      when: ansible_distribution == "CentOS"

    - name: isntall packages
      apt: name={{item}} state=present
      with_items:
        - vim
      when: ansible_distribution == "Ubuntu"
